name: Build Docker Image       
on:
#  Triggers the workflow on push request events but only for the devops branch
  push:
    branches:
      - master
jobs:
# This workflow contains multiple jobs
 Build:
  name: BuildApp
# The type of runner that the job will run on testing
  #runs-on: ubuntu-latest
  runs-on: self-hosted
  #runs-on: shaun-windows-runner
  #runs-on: windows-latest
  steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   - name: Checkout Repository
     uses: actions/checkout@v3
       
   - name: Setup .Net core
     uses: actions/setup-dotnet@v3
     with:
       dotnet-version: '6.0'

   - name: Build
     run: dotnet build
       
 
